# Generated by Django 4.2.6 on 2023-11-08 06:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_work_blog_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_comment',
            name='dop',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
