# Generated by Django 4.2.6 on 2023-11-09 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_blog_comment_dop'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_comment',
            name='comment_count',
            field=models.ImageField(default=0, upload_to=''),
        ),
        migrations.AddField(
            model_name='blog_comment',
            name='like_count',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
