# Generated by Django 4.2.6 on 2023-11-27 06:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_cart_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 27, 6, 42, 47, 725884, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2023, 11, 27, 12, 12, 47, 725885), null=True),
        ),
    ]
