# Generated by Django 4.2.6 on 2023-11-29 06:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_cart_created_on_alter_transaction_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 29, 6, 11, 11, 744283, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2023, 11, 29, 11, 41, 11, 745281), null=True),
        ),
    ]
